democracyworks/kehaar

- .travis.yml
- ChangeLog.md
- README.md
- project.clj
- src/kehaar.clj
- test/kehaar/rabbit_mq_test.clj
- test/kehaar_test.clj
The ChangeLog has a pretty detailed explanation of what's happened. Generally:
* None of the functions at this level of abstraction declare Rabbit queues anymore (that *could* happen in future functions that call these).
* Function signatures have been rationalized (`rabbit->async` and `async->rabbit` now look like the other, for example).
* Some light renaming.
* Tests that actually exercise RabbitMQ have been added.
This branch has been released as 0.2.0-SNAPSHOT (though that is not represented in the project.clj).
If merged, the project.clj should be updated to 0.2.0 and a new release to clojars should be pushed out.
> Refactoring

- project.clj
- src/kehaar.clj
When you take nil from a core.async channel, that means it is closed. So we should stop looping when that happens and not process the nil value.
> Stop looping on nil take

- README.md
- src/kehaar/core.clj
- test/kehaar/core_test.clj
- test/kehaar/rabbit_mq_test.clj
Same as before*, but now with 100% less version bumping and 100% more README updating (and opportunistic typo fixes).
*Where "before" is fixing the single-level namespace as recommended by http://clojure-doc.org/articles/language/namespaces.html
> Fix single level namespace

- ChangeLog.md
- project.clj
- src/kehaar/core.clj
- test/kehaar/core_test.clj
- test/kehaar/rabbit_mq_test.clj
This is an attempt to improve upon and debug the issue I'm seeing in production where, when a kehaar-using component has been running for awhile it will stop consuming incoming messages. They will arrive on the Rabbit queue, and kehaar will get them, but then it auto-acks them, tries to >!! them onto the core.async channel, and then (presumably) blocks forever.
See individual commits for details.
> Add logging and ack on take

- ChangeLog.md
- README.md
- src/kehaar/core.clj
- test/kehaar/core_test.clj
- test/kehaar/rabbit_mq_test.clj
This reverts commit c748a4b2190fa2aae3937e3066861c3a766bbaeb.
We decided it was better to return a core.async channel after all.
Example use case: Consuming the responses in a go block allows the go
block's thread to park when using a channel, but it will block and tie
up the thread if you're using a promise.
Is this the cleanest way to do this (in git)? I'm conflicted. Maybe this is a good example of why changelog edits should be their own commits?
> Revert to chan in response fns

- README.md
- src/kehaar/wire_up.clj
Our creation and wiring up of queues, handlers, and channels was getting
hairy. We had several patterns that we were repeating across
projects. These functions codify those patterns with descriptive
names. The goal is to make it easier to write and read queue wire-ups.
All of these functions are in the `kehaar.wire-up` namespace, intended
to be aliased as `wire-up`. That makes their usage read like
English. Example:
```
(wire-up/incoming-service-handler ...)
(wire-up/incoming-events ...)
```
All of these wire-up functions return the langohr channel they opened.
> Wiring helpers to shorten + clarify queue declarations.

- README.md
- src/kehaar/async.clj
- src/kehaar/core.clj
- src/kehaar/wire_up.clj
- test/kehaar/core_test.clj
- test/kehaar/rabbit_mq_test.clj
- test/kehaar/wire_up_test.clj
This is a major change. It renames and reworks the existing
functionality.
The main motivation for this was to make kehaar more robust when faced
with errors. EDN parse errors would cause the entire handler to
crash. And kehaar would read as many messages as it could at a time,
potentially overloading the server with no recourse for backpressure.
This rewrite solves those two problems while renaming and reworking the
abstractions. The main difference is that the functions which pump
messages to and from rabbit <=> core.async now pass the payload *and*
metadata. This simplified the code a lot since we often need the
metadata.
Event handlers and service responders now run in their own threads. call
`start-event-handler!` and `start-responder!` in server initialization
to start those. The …
> Backpressure

- ChangeLog.md
- README.md
- src/kehaar/core.clj
- src/kehaar/rabbitmq.clj
- test/kehaar/rabbit_mq_test.clj
This moves some boilerplate code we've been repeating in every kehaar project into the library itself.
Between this and @ericnormand's new `wire-up` ns, it makes the `queue/initialize` fn much shorter. Here's a before and after from a new kraken-works component:
```clojure
(ns new-kraken-works.queue
(:require [langohr.core :as rmq]
[langohr.channel :as lch]
[langohr.queue :as lq]
[kehaar.core :as k]
[clojure.tools.logging :as log]))
(defn initialize []
(let [connection (atom nil)
max-retries 5]
(loop [attempt 1]
(try
(reset! connection
(rmq/connect (or (config :rabbitmq :connection)
{})))
(log/info "RabbitMQ connected.")
(catch Throwable t
(log/warn "RabbitMQ not available:" (.getMessage t) "attempt:" attempt)))
(when (nil? @connection)
(if (< attempt max-retries)
(do (Thread/sleep (* …
```
> add connect-to-broker fn

- src/kehaar/wire_up.clj
- test/kehaar/wire_up_test.clj
These are the options we use everywhere, and seem to make more sense to me even in the context of this open-source, general-purpose library. But if others feel differently, there are other ways to improve upon this. Currently the workaround is to use the higher-arity version everywhere. But as it is, I'm not sure the lower-arity version would be useful to anyone (or at least, it isn't to us).
> default to more typical queue options in wire-up/external-service

- test/kehaar/rabbit_mq_test.clj
- test/kehaar/test_config.clj
- test/kehaar/wire_up_test.clj
Adds a `kehaar.test-config` ns for either using environment vars or default localhost/5672 config; re-named "events" exchange to "test-events" to avoid collision (when using krakenstein RabbitMQ as your test instance, in my case).
Understand that the latter may be more appropriate as a second PR, assuming this is acceptable at all--happy to do that or whatever is needed.
> RabbitMQ config for tests

- ChangeLog.md
- README.md
- example/project.clj
- example/src/kehaar_example/streaming/producer.clj
- src/kehaar/core.clj
- src/kehaar/wire_up.clj
- test/kehaar/core_test.clj
- test/kehaar/wire_up_test.clj
Instead of a single thread that spawns new threads for every message it receives, the message handler functions (`start-responder!`, `start-streaming-responder!`, and `start-event-handler!`) now spawn a fixed number of threads to handle messages.
Additionally, whenever `rabbit=>async` is unable to place a message from rabbit onto a core.async channel, after it nacks, it sleeps for a second before trying again. This will be configurable and fancy at a later date.
> Configurable number of threads to handle messages

- README.md
- src/kehaar/core.clj
- src/kehaar/wire_up.clj
Using `async->fire-and-forget-fn` will result in the incoming-service on the other side to warn every time a message is sent. Setting `ignore-no-reply-to` lets the service suppress those warnings, if it can know that it will be often used for fire-and-forget.
> Add ignore-no-reply-to to incoming-service

- README.md
- docs/wire-up.md
- example/src/kehaar_example/streaming/producer.clj
- src/kehaar/configured.clj
- src/kehaar/core.clj
- src/kehaar/wire_up.clj
- test/kehaar/wire_up_test.clj
Before, to decide whether or not to use a bespoke queue for a streaming response, the code would check the response collection to see if it had at least as many elements as the `threshold`. If it was smaller, responses would go out on the shared response queue. If it had at least that many, responses would go out on a bespoke queue. However, the time to realize that many elements could take longer than the `timeout`, resulting in a timeout response even though the time between any two elements wouldn't be greater than the timeout.
With these changes, the elements before the `threshold` will be sent on the shared response queue, switching over to a bespoke queue once the number of elements sent so far reaches the threshold number.
Previously, a streaming responder needed to return a …
> Streaming improvements

- project.clj
- src/kehaar/configured.clj
- src/kehaar/response_queues.clj
- src/kehaar/wire_up.clj
Server-named queues set up by kehaar for use with responders need to be tracked so that kehaar can set the correct reply-to queue for requests when those queues get renamed during a Rabbit recovery from a failure state.
This keeps track of a mapping from an external service queue name to the name of the server-named queue for responses. State is kept in an atom holding a bidirectional map, and convenience functions are provided for interacting with it.
When Rabbit renames a server-nemed queue, a callback updates the state if necessary.
Short-lived server-named queues are not tracked. You better believe that a service will time out waiting for an answer before Rabbit can recover. It is not fast.
This recovery only happens for clients using the `kehaar.configured/init!` function.
```
... …
```
> Recovery of long lived server-named queues

- src/kehaar/rabbitmq.clj
- test/kehaar/rabbit_mq_test.clj
- test/kehaar/wire_up_test.clj
While trying to diagnose krakenstein flakiness on Marla's machine, we saw several components fall over due to `java.util.concurrent.Timeout` exceptions being thrown and not retried. It seemed like this was exactly the kind of thing `connect-with-retries` was intended to make more robust. Hence this PR.
This should help krakenstein come up more often without manual intervention.
When I went to run the tests after adding this, I found a broker-requiring test that had snuck into a `deftest` form without the `^:rabbit-mq` metadata set on it. So I also fixed that.
> More connect retries

- project.clj
This is primarily motivated by bringing in a version of core.async that passes clojure 1.9.0-alpha17's specs.
I had a project not compiling under 1.9.0-alpha17 because it pulled in kehaar but not core.async.
OK if I update the changelog and example project and push a 0.10.5 release with these updates?
> Update deps to latest versions we want

- src/kehaar/core.clj
- src/kehaar/edn.clj
- src/kehaar/jobs.clj
- test/kehaar/core_test.clj
- test/kehaar/edn_test.clj
Adds new pr-str and read-string drop-in replacements that sanitize encoded values of regexen before encoding them into EDN strings and doesn't throw exceptions on unknow tags, respectively. Uses them throughout kehaar.
> Use safer EDN encoding and reading

- src/kehaar/core.clj
- src/kehaar/wire_up.clj
Replace old `thread-handler` code that pre-allocated a pool of threads, each trying to take work from a core.async channel, with a system that spawns threads as work is available, using a semaphore to limit the number of live threads at a given time.
The threads spawned now will be deallocated at the end of the work they do[1], making it easier to find threads actually doing stuff in a Java profiler.
[1]: Well, core.async is a little smarter than just deallocating a thread when it's finished. it will be held on to for a time and reused if new work comes around quickly. After some amount of time, if no new work shows up, it'll be killed.
> Allow "handling" threads to be released when not in use

- README.md
- example/project.clj
- example/src/kehaar_example/core.clj
- example/src/kehaar_example/jobs/counter.clj
- example/src/kehaar_example/jobs/instigator.clj
- example/src/kehaar_example/jobs/threes.clj
- example/src/kehaar_example/streaming/consumer.clj
- example/src/kehaar_example/streaming/producer.clj
- src/kehaar/configured.clj
Anywhere a `kehaar.configured` initialzation function used to take a symbol that named a function or channel can now take the actual function or channel itself.
> Allow real values in configured where symbols go

- ChangeLog.md
- project.clj
> Update Langohr to 4.1.0

- ChangeLog.md
- project.clj
- src/kehaar/rabbitmq.clj
- test/kehaar/rabbitmq.clj
- test/kehaar/rabbitmq_test.clj
Hopefully the changelog addition explains the _what_. As for the _why_, we ran into a need for something like this with components that connect to CloudAMQP in one env but to our (very default-y) RabbitMQ clusters in another.
> Add blank config param helper fn

- src/kehaar/configured.clj
- test/kehaar/configured_test.clj
- test/kehaar/not_yet_required.clj
Currently when developing at a repl, you can't redefine kehaar handlers that are set up with `kehaar.configured`. This PR uses clojure vars for handler functions when possible, which allows using a reload repl workflow.
`realize-symbol-or-self` is wrapped twice: `realize-fn` for functions (which can be replaced by vars naming functions), and `realize-chan` for async channels (which need to be actual channels). 
This behavior can be turned on by setting an env var: `KEHAAR_DEBUG`, though I'm open to feedback on other ways to control this behavior.
> Debug handlers

- src/kehaar/core.clj
- src/kehaar/wire_up.clj
- test/kehaar/streaming_test.clj
Kehaar streaming has a couple of race conditions. The first commit of this PR is a set of failing tests -- the straightforward tests passed already, but the tests that introduce artificial timing issues failed.
The main problem is that while we were correctly setting a prefetch of 1 on a channel, we used a different channel to get responses from the queue, causing messages to come out of order. This PR also fixes a couple of edge cases where streaming channels and queues were not cleaned up.
> Fix race conditions in streaming

- src/kehaar/core.clj
- test/kehaar/streaming_test.clj
The RabbitMQ Java client does channel and topology recovery when it
detects connection issues. This includes declaring any queue that was
declared by this connection, but that was not deleted by the connection.
Since bespoke streaming response queues are created by the responder,
but deleted by the consumer, the responder has no way of knowing that
the queue was deleted. This means that when the responder handles
automatic recovery, it re-declares every bespoke response queue it has
ever created.
The idea behind the test is straightforward, but the implementation is a little tricky. I went through a couple iterations to make it as deterministic as possible -- for comparison, see an [earlier attempt](https://github.com/democracyworks/kehaar/commit/a6c83e8fe5a10a94f74589799db69a49ec2d0842). …
> Do not recover streaming response channels
